name = "QInterpolate"
uuid = "1f9e2ed0-874e-11e9-3621-57bc601552eb"
authors = ["neversakura <neversakura@hotmail.com>"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
